"""Adding New Datatype

Revision ID: f156bfa421c9
Revises: 1f69dff8b72e
Create Date: 2023-10-27 16:53:27.636969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f156bfa421c9'
down_revision: Union[str, None] = '1f69dff8b72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_file_name'), ['file_name'], unique=False)

    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('cluster_label', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['processed_texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clusters_file_name'), ['file_name'], unique=False)

    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['processed_texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_embeddings_file_name'), ['file_name'], unique=False)

    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_text', sa.Text(), nullable=True),
    sa.Column('entity_label', sa.String(), nullable=True),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['processed_texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entities')
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embeddings_file_name'))

    op.drop_table('embeddings')
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clusters_file_name'))

    op.drop_table('clusters')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_file_name'))

    op.drop_table('topics')
    # ### end Alembic commands ###
